version: "3"

services:
  postgres:
    image: postgres:14
    ports:
      - 5432:5432
    restart: always
    user: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: password
    volumes:
      - ${PWD}/seed.sql:/docker-entrypoint-initdb.d/seed.sql
      - postgres:/var/lib/postgresql/data
    
volumes:
  postgres: ~
